# Generated by Django 2.1.3 on 2019-02-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
