# Generated by Django 2.1.3 on 2019-02-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exit', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exit.Survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='survey',
            name='batches',
            field=models.ManyToManyField(to='users.Batch'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subject'),
        ),
        migrations.AddField(
            model_name='squestionresponse',
            name='squestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exit.SQuestion'),
        ),
        migrations.AddField(
            model_name='squestionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exit.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='squestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exit.Survey'),
        ),
    ]
